-- Student: UDISE, parent Aadhaar, occupations, PEN, bank details

ALTER TABLE students ADD COLUMN IF NOT EXISTS udise_no VARCHAR(32) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS father_aadhar_no VARCHAR(20) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS mother_aadhar_no VARCHAR(20) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(200) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(200) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS pen_no VARCHAR(64) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS bank_name VARCHAR(200) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS bank_account_no VARCHAR(64) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS bank_ifsc VARCHAR(20) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS bank_branch VARCHAR(200) NULL;
